// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar 100% autogerada a partir da estrutura de pastas em /docs
  // Basta criar pastas e arquivos .md e a sidebar se atualiza sozinha.
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
